services:
  # A Docker web service
  - type: web
    name: fnd_gui
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
      #python download_model.py &&  # Check if model exists and download if not
